apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: kcs7050303
  labels:
    machineconfiguration.openshift.io/role: master
spec:
  config:
    ignition:
      version: 3.1.0
    systemd:
      units:
        - name: kcs7050303.service
          enabled: true
          contents: |
            [Unit]
            Description=Remove the leftover network files
            Before=NetworkManager.service

            [Service]
            Type=oneshot
            ExecStart=/bin/bash -x -c 'rm -f /run/configure-ovs-boot-done && (mv /etc/NetworkManager/system-connections/ovs-if-br-ex* /root 2>dev/null ||true)'
            StandardOutput=journal

            [Install]
            WantedBy=multi-user.target