apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: kcs7050303
spec:
  config:
    ignition:
      version: 3.1.0
    systemd:
      units:
        - name: kcs7050303.service
          enabled: true
          contents: |
            [Unit]
            Description=Move OpenvSwitch config files and reboot
            After=network-online.target

            [Service]
            Type=oneshot
            ExecStart=/bin/bash -c 'journalctl -u ovs-configuration.service | grep "ERROR: could not find ovs-if-br-ex conn file after cloning" >/dev/null && \
              mv /etc/NetworkManager/system-connections/ovs-if-br-ex* /root && \
              reboot'
            StandardOutput=journal

            [Install]
            WantedBy=multi-user.target
  osImageURL: quay.io/openshift-release-dev/ocp-release:latest
  kernelType: ""
