apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: run-error-watcher-script
spec:
  config:
    ignition:
      version: 3.1.0
    systemd:
      units:
      - name: run-error-watcher-script.service
        enabled: true
        contents: |
          [Unit]
          Description=Run OpenvSwitch Error Watcher script
          After=network-online.target

          [Service]
          Type=oneshot
          ExecStart=/usr/bin/python3 /usr/local/bin/kcs7050303.py
          StandardOutput=journal

          [Install]
          WantedBy=multi-user.target
  osImageURL: quay.io/openshift-release-dev/ocp-release:latest
  kernelType: ""